config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :events

  root :to => 'core#home'
  
  get '/home', :to => 'core#home'
  get '/news', :to => 'core#news'
  get '/what_we_do', :to => 'core#what_we_do'
  get '/whats_on', :to => 'events#index'
  get '/shop', :to => 'core#shop'
  get '/contact', :to => 'core#contact'
  
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
  belongs_to :event
  
end

app/models/event.rb
class Event < ActiveRecord::Base
  
  validates_presence_of :title, :date, :description
  
  has_many :comments, :dependent => :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def index
    
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    #@comments = Comment.all
    #@event = Event.find(params[:id])
    #@comments = Comment.where(event_id: params[:id])
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new(event_id: params[:event_id])
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:event_id, :details, :author)
    end
end

app/controllers/core_controller.rb
class CoreController < ApplicationController
  def home
  end

  def news
  end

  def what_we_do
  end

#   def whats_on
#   end

  def shop
  end

  def contact
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:event_id])
    @comments = Comment.where(event_id: params[:event_id])
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :date, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/fobh_core_controller_helper.rb
module FobhCoreControllerHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<%= f.hidden_field :event_id %>
  <div>
    <table id='entryform'>
      <tr>
        <td><%= f.label :author %></td>
        <td><%= f.text_field :author %></td>
      </tr>
      <tr>
        <td><%= f.label :details %></td>
        <td><%= f.text_area :details %></td>
      </tr>
    </table>

    <span id='button'><%= f.submit %></span>
  </div>

<% end %>

app/views/comments/_index.html.erb
  <% #comments.each do |comment| 
%>
  <div id='comment'>
    <table style='width:100%;'>
      <tr style='width:100%;'>
        <td>
          <h2><%= comment.author %></h2>
        </td>
        <td id='links'>
          <%= link_to 'Edit', edit_comment_path(comment) %> 
          <%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    </table>
    <p>
      <%= comment.details %>
    </p>
  </div>  
  <% #end 
%>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render 'form' %>

<p>
  <%= link_to 'Preview', @comment %> | <%= link_to 'Go Back', events_path %>
</p>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<p>
  <%= link_to 'Go Back', events_path %>
</p>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>


<h1>This comment</h1>

<h2><%= @comment.author %></h2>

<p><%= @comment.details %></p>

<p>
  <%= link_to 'Edit', edit_comment_path(@comment) %> |
  <%= link_to 'Go Back', events_path %>
</p>

app/views/core/contact.html.erb
<title>TFoBH | Contact</title>

<h1>Contact</h1>
<p>Some stuff goes here</p>

app/views/core/home.html.erb
<title>TFoBH | Home</title>

<!-- <div id='home-feature' style='border-bottom: black 2px solid;'> -->
  <div id='background' style='position: absolute; left:0; padding-bottom:10px;'>
    <%= image_tag("boxhillhome3.jpg", :alt => "View from top of Box Hill") %>
  </div>

  <div style='position:relative; min-height: 309px;'>

    <h1>
      Home
    </h1>

    <div style='position: absolute; right: +0px; top: +0px;'>
      <div id='infobox'>
        <h1>A view worth seeing</h1>
        <p>Words can't truly explain the sight from the top of Box Hill, we find a picture works better!</p>
      </div>
      <div id='infobox'>
        <h1>Look pretty?</h1>
        <p>Click <%= link_to "here", contact_path %> to learn more about the beauty of Box Hill.</p>
      </div>
      <div id='infobox'>
        <h1>"I want more"</h1>
        <p>Great! Have a look around the rest of our site for more info on us and all we do.</p>
      </div>
    </div>

  </div>
<!-- </div> -->

<table id='main'>
  <tr>
    <td>
      <h2>A quick introduction</h2>
      <p>
        Box Hill is remarkable for many reasons, provides a powerful way to help you prove your point. When you click Online Video, you can paste in the embed code for the video you want to add.
      </p>
    </td>
    <td>
      <h2>Empowering you</h2>
      <p>
        Whether it's a challenge, a race, or just a leisurely walk, we know how amazing it feels to climb such an iconic landmark. We'll see you at the top!
      </p>
    </td>
    <td>
      <h2>Situated in Surrey</h2>
      <p> We're in North-East Surrey, not far from Guildford and just a couple miles from the M25. For instructions on how to get here just type 'Box Hill' into any route planner. See you soon.
      </p>
    </td>
  </tr>
</table>

app/views/core/news.html.erb
<title>TFoBH | News</title>

<h1>News</h1>
<p>Some stuff goes here</p>

app/views/core/shop.html.erb
<title>TFoBH | Shop</title>

<h1>Shop</h1>
<p>Some stuff goes here</p>

app/views/core/what_we_do.html.erb
<title>TFoBH | What We Do</title>

<h1>What We Do</h1>
<p>Some stuff goes here</p>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_show.html.erb
<div id='event'>
  <table style='width:100%;'>
    <tr>
      <td><h2>
        <%= #link_to event.title, event 
        %>
        <%= event.title %>
        </h2></td>
      <td style='text-align:right;'><h2><%= event.date %></h2></td>
    </tr>
  </table>

  <p><%= event.description %></p>
  <button id ='
               <%= event.id %>
               ' onClick='showComments(this.id)'>
    Show Comments
  </button>
  <button>
    <%= link_to 'New Comment', new_comment_path(event_id: event) %>
  </button>
  <button>
    <%= link_to 'Edit', edit_event_path(event) %>
  </button>
  <button>
    <%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' } %>
  </button>
  
  <div id='comments' class='
                            <%= event.id %>
  '>
  <h1>Comments</h1>

  <% 
    @comments = Comment.where(event_id: event)

    @comments.each do |comment|
  %>

    <%= render 'comments/index', comment: comment %>

  <% end %>
    
  </div>
    
</div><!-- event -->

app/views/events/edit.html.erb
<title>TFoBH | What's On | Edit</title>

<h1>Edit Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<title>TFoBH | What's On</title>

<h1>What's On</h1>

<% @events.each do |event| %>
    
    <%= render 'show', event: event %>

<% end %>

<button class='big'>
  <%= link_to 'New Event', new_event_path %>
</button>

app/views/events/new.html.erb
<title>TFoBH | What's On | New</title>

<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='centered smallprint'>
    &copy The Friends Of Box Hill
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class='centered'>
    <table>
      <tr>
        <td>
          <%= link_to image_tag("logo.png", :alt => "logo"), home_path %>
        </td>
        <td>
          <h1>
            The Friends Of Box Hill
          </h1>
        </td>
      </tr>
    </table>
  </div>
</header>

app/views/layouts/_navigation.html.erb
<nav>
  <ul class='centered'>
    <li><%= link_to "Home", index_path %></li>
    <li><%= link_to "News", news_path %></li>
    <li><%= link_to "What We Do", what_we_do_path %></li>
    <li><%= link_to "What's On", events_path %></li>
    <li><%= link_to "Shop", shop_path %></li>
    <li><%= link_to "Contact", contact_path %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,400,700,300,800' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render 'layouts/header' %>
  <%= render 'layouts/navigation' %>
  
  <div id='content' class='centered'>
    <%= yield %>
  </div>
  
  <%= render 'layouts/footer' %>

</body>
</html>